### ISSUE TITLE
OOD-track-mysteryann error

### ISSUE THREAD

**Issue by 123kuangyu** [matchyc/mysteryann#3]
When I use the following command line instruction：
python install.py --neurips23track ood       --algorithm mysteryann
python run.py --neurips23track ood       --algorithm mysteryann --dataset random-xs

The following error occurs：
![1734336027424](https://github.com/user-attachments/assets/272f5d5d-aac6-41d2-8455-f1ced26fa776)

My computer configuration uses WSL2 + Ubuntu 22.04 environment, Looking forward to your reply，thank you.

**Comment by matchyc** [comment]
Hi, thanks for your interest.
I believe the code works on the competition framework since it was executed by the organizers for evaluation.
I can give some points for your experiments.
1. The code requires AVX2/AVX512 and is not compatible with other architectures. Please refer to the official machine used in the competition.
2. The test on WSL has not ever been conducted, so I am afraid that I can't give more comments on this.
3. If you are interested in the algorithm itself and the insights we obtained in the OOD research, I recommend you refer to our paper RoarGraph: https://arxiv.org/abs/2408.08933. This paper's codebase can be run without the competition framework.

**Comment by 123kuangyu** [comment]
Thank you for your reply. I changed to a native ubuntu18.04 machine and ran and tested the corresponding code, which solved the above error.
